### ISSUE TITLE
Per me non funziona

### ISSUE THREAD

**Issue by blakdog1978** [sdavides/meian-Siqura_CasaSicuraAlarm-Homeassistant#1]
Buongiorno,
stavo facendo delle prove per integrare il mio allarme ma non mi funziona forse perchè le pagine html per la mia centrale " Defcon 8 " con scheda FC-7688 -PLUS sono diverse. Ci stavo riuscendo egregiamente con l'addon di Maxill1 https://github.com/maxill1/ialarm-mqtt ma ora dopo gli aggiornamenti che ha fatto home assistant per mqtt sta dando problemi e presto credo smetterà di funzionare.
Dici che potresti far qualcosa per aiutarmi?

**Comment by Stefano201** [comment]
che problemi hai riscontrato?

**Comment by sdavides** [comment]
senza risposta
