### ISSUE TITLE
Ialarm mk

### ISSUE THREAD

**Issue by mistermax80** [sdavides/meian-Siqura_CasaSicuraAlarm-Homeassistant#2]
Ciao ho ialarm, non capisco che io devo inserire e se la pagina htm é corretta.
Il mio allarme lavora su una porta specifica e volevo provare tramite rest.
Che ip e porta devo usare? Come posso capirlo?
Dall'app e dalla custom integration usano un ip (internet) fisso. Devo usare quello pubblico o locale? E la porta come la inserisco? Immagino che dovrebbe rispondermi anche da browser prima di provare da HA.

**Comment by sdavides** [comment]
se esiste una pagina per il tuo allarme sicuramente devi aprirlo dal browser dall'IP locale.
Quindi guarda quale ip 198.168.1.x che prende sul tuo modem.
Poi prova http:// o https://

**Comment by sdavides** [comment]
mi sembra di ricordare che l'ultimo ialarm non ha pagina, quale centralina hai?

**Comment by mistermax80** [comment]
Ialarm xr é l'ultima del 2024...
La libreria che uso al momento é https://github.com/wildstray/meian-client.
Uso un integrazione fornita da antifurto365, ma vedo solo lo stato dell'allarme e posso inserirlo e toglierlo. Mi interessava visualizzare i sensori.
Qualche suggerimento per usare la tua libreria?

**Comment by sdavides** [comment]
da quello che ho letto la XR non ha la pagina web.

Ciao

**Comment by mistermax80** [comment]
Scusami in realtà la mia è mk che é la più evoluta da un punto di vista tecnico... Ma credo funzioni uguale.
Grazie puoi chiudere!
