### ISSUE TITLE
funzionamento con tutte le versioni nuove dell'antifurto casasicura?

### ISSUE THREAD

**Issue by ortorob73** [sdavides/meian-Siqura_CasaSicuraAlarm-Homeassistant#3]
Ciao

recentemente casasicura ha rilasciato una nuova centrale Siqura denominata Platinum ( vedi qui [https://www.casasicura.it/kit-antifurto-casa.html](https://www.casasicura.it/kit-antifurto-casa.html ).

Qualcuno ha già provato il flow anche su tale versione?

Grazie

**Comment by sdavides** [comment]
si

https://github.com/indomus/forum/discussions/239#discussioncomment-9213112
