### ISSUE TITLE
Quesito

### ISSUE THREAD

**Issue by alessandroadorna** [sdavides/meian-Siqura_CasaSicuraAlarm-Homeassistant#4]
Ciao Davide. Ti scrivo per ringraziarti della guida, con qualche tentativo extra sono riuscito a far funzionare la centralina e l'unico sensore presente. Come ti dicevo, dai tuoi screens la plancia visualizza gli attributi di ogni scheda aggiunta. Nel mio caso devo cliccare su ogni voce e poi su Attributi per visualizzare i valori. Come posso risolvere? Ti ringrazio

![plancia](https://github.com/user-attachments/assets/9fee8092-f1c7-4fc0-b844-32d6ec1a4fdd)

**Comment by sdavides** [comment]
è un componente aggiuntivo di homeassistant che si chiama more-info-card

**Comment by alessandroadorna** [comment]
perfetto, ti ringrazio, lo provo subito

**Comment by alessandroadorna** [comment]
Sembra che non basti solo scaricare il componente.. ci sono passaggi di codice da inserire se non ho capito male.. :-(

**Comment by sdavides** [comment]
Éé?? Sembra che non sei in grado, lascia perdere homeassistant

**Comment by alessandroadorna** [comment]
ti ringrazio per esserti preso del tempo per rispondere alle mie domande. Comprendo la tua risposta finale ma la vita mi ha insegnato a non gettare la spugna al primo ostacolo, motivo per il quale chiedo, scrivo, leggo, ecc.
Ho risolto in merito a quanto sopra, leggendo meglio la pagina delle istruzioni del componente aggiuntivo: bastava inserire la riga di codice alla riga delle entità. Potevo arrivare alla soluzione se me l'avessi indicato, forse con una frase, massimo 2 oppure insistendo e capendo meglio il da farsi. In effetti mi sto affacciando da poco al mondo di Home Assistant.
Eviterò di scriverti in futuro. Ti auguro il meglio.

**Comment by sdavides** [comment]
Si certo, ma nessuno mi paga,non posso perdere tempo anche a spiegare le nozioni base di homeassistant con altri 30 post, se non conoscevi il file base delle configurazioni mi chiedo come hai configurato il resto e il pannello allarme mqtt.

**Comment by alessandroadorna** [comment]
con la tua guida, passo passo, tra l'altro fatta bene.
