### ISSUE TITLE
Problema in fase di installazione

### ISSUE THREAD

**Issue by danieleburani** [sdavides/meian-Siqura_CasaSicuraAlarm-Homeassistant#5]
Ciao Davide, 
ho letto il tuo procedimento per estendere CASA SIQURA in Home Assistant, ma essendo abbastanza un neofita non riesco a venirne a capo. 
Avresti tempo e voglia di aiutarmi di supportarmi? 
Grazie mille 

Daniele

**Comment by sdavides** [comment]
È scritto tutto sul pdf, a gratis non lo so

**Comment by alessandroadorna** [comment]
Ciao Davide, per un eventuale supporto a pagamento, possiamo sentirci in privato?

**Comment by sdavides** [comment]
Si con teams da remoto

**Comment by sdavides** [comment]
Ma è la centralina dell immagine o un altro modello?

**Comment by alessandroadorna** [comment]
A quale immagine ti riferisci? Comunque è una Siqura Platinum, ovvero una versione aggiornata della WEB ma con modulo 4G integrato. Ho caricato il tuo flusso e funziona tutto tranne quando vado ad aggiungere un ulteriore sensore oltre gli 8 che sono presenti da tua configurazione.

**Comment by sdavides** [comment]
![immagine](https://github.com/user-attachments/assets/7b6c24f7-bf0f-4adb-a83b-226bc187ffb6)

**Comment by alessandroadorna** [comment]
Potresti inviarmi un tuo account PayPal?
Grazie

Il giorno mer 16 ott 2024 alle 17:43 sdavides ***@***.***> ha
scritto:

**Comment by sdavides** [comment]
Non so come si scrive in privato su git

**Comment by alessandroadorna** [comment]
scrivimi qui:

***@***.***



Il giorno mer 16 ott 2024 alle 18:13 sdavides ***@***.***> ha
scritto:

**Comment by sdavides** [comment]
non si vede è asteriscato

**Comment by alessandroadorna** [comment]
a l e s s a n d r o a d o r n a       g m a i l

**Comment by alessandroadorna** [comment]
la mia email è semplice:   nome cognome

**Comment by sdavides** [comment]
it o com?

**Comment by alessandroadorna** [comment]
C o m

Il giorno mer 16 ott 2024 alle 18:46 sdavides ***@***.***> ha
scritto:

**Comment by sdavides** [comment]
Con questo puoi accedere alla pagina della centralina da home assistant.

https://github.com/sdavides/NginxReverse-Homeassistant

![immagine](https://github.com/user-attachments/assets/8b5f717c-dfad-4f27-b718-69477f7e9388)

**Comment by alessandroadorna** [comment]
Benissimo, grazie, lo proverò presto.

Il giorno gio 17 ott 2024 alle 15:45 sdavides ***@***.***> ha
scritto:
