### ISSUE TITLE
voci sul menu Sistema non corrette

### ISSUE THREAD

**Issue by alessandroadorna** [sdavides/meian-Siqura_CasaSicuraAlarm-Homeassistant#6]
![aaaaa](https://github.com/user-attachments/assets/79007db8-fe25-4268-baf2-6d10a383c564)

**Comment by sdavides** [comment]
Hai un modello differente, dovrei avere la tua centralina per correggerlo, così non posso proprio aiutarti.
Cos'è l'addon che hai "JX" ?
è di casasicura? Puoi inviarmelo?

**Comment by alessandroadorna** [comment]
Si tratta dell'ADD-ON di Tuya per aggiungere i scenari che riguardano la Siqura JX, niente di che.

![image](https://github.com/user-attachments/assets/23cdab05-fc41-43b1-a24f-052ff2f91599)

**Comment by alessandroadorna** [comment]
se può essere di aiuto un recente firmware della Platinum ha introdotto una funziona in più:


![image](https://github.com/user-attachments/assets/ad40a7bf-21c0-4a17-866a-9563e63e0ed7)

**Comment by sdavides** [comment]
Puoi inviarmi il file firmware?

**Comment by alessandroadorna** [comment]
[T_Panel 050624 bug LAN 10mbps.zip](https://github.com/user-attachments/files/17459617/T_Panel.050624.bug.LAN.10mbps.zip)

**Comment by sdavides** [comment]
> [T_Panel 050624 bug LAN 10mbps.zip](https://github.com/user-attachments/files/17459617/T_Panel.050624.bug.LAN.10mbps.zip)
> 

Ciao, oltre a questo,hai anche il file web....bin ? Posso chiederti dove hai trovato lo zip?

**Comment by sdavides** [comment]
ho rifatto il flusso node-red, elimina e reimporta il json, prova con questo se sono risolti i dati errati

**Comment by alessandroadorna** [comment]
Ci proverò domani, ti ringrazio 🤗

Il giorno gio 31 ott 2024 alle 22:55 sdavides ***@***.***> ha
scritto:

**Comment by alessandroadorna** [comment]
> > [T_Panel 050624 bug LAN 10mbps.zip](https://github.com/user-attachments/files/17459617/T_Panel.050624.bug.LAN.10mbps.zip)
> 
> Ciao, oltre a questo,hai anche il file web....bin ? Posso chiederti dove hai trovato lo zip?

[web 13052024 con reboot pianificato.zip](https://github.com/user-attachments/files/17619001/web.13052024.con.reboot.pianificato.zip)

**Comment by sdavides** [comment]
grazie, ho fatto l'aggiornamento, devo mettere anche un file audio?

su l'opzione audio e riavvio programmato di mide !DEF

**Comment by alessandroadorna** [comment]
No lì nulla

Non è supportata da questa centralina


Il flusso nuovo non sembra risolvere quanto sopra..

Il giorno lun 4 nov 2024 alle 18:04 sdavides ***@***.***> ha
scritto:

**Comment by sdavides** [comment]
lo testato ora e funziona correttamente a me, hai rimesso nome utente e password dentro i nodi http?

**Comment by alessandroadorna** [comment]
Ho aggiornato l’indirizzo io della centralina ma nome utente e pw no..
provvedo
Grazie

Il giorno lun 4 nov 2024 alle 18:13 sdavides ***@***.***> ha
scritto:

**Comment by sdavides** [comment]
Ultima cosa, ma dov'è l opzione sulla pagina web che invece trovo sulla app per impostare un sensore a muto,continua o a impulsi la sirena?

**Comment by alessandroadorna** [comment]
Domani ti invio screen (Comunque su Gestione Zone)

Il giorno lun 4 nov 2024 alle 18:39 sdavides ***@***.***> ha
scritto:

**Comment by sdavides** [comment]
trovato, i dati sono corretti ora? posso chiudere?
